// =============================================================
//  lib/rolesPermissions.js (0.62.121)
//
//  Catalogue COMPLET des permissions du soft Aveho EC :
//  - Côté ÉTABLISSEMENT (PSAD client) : patients, mat, intervs, etc.
//  - Côté MAGASIN (PSAD fournisseur) : catalogue, achats, transferts
//  - Côté COMMUN : admin, paramètres, RGPD, audit
//
//  Templates de rôles pré-configurés pour démarrer rapidement.
// =============================================================

// === CATÉGORIES ET MODULES ===
// chaque module : k (clé), l (label), ic (icône Tabler), c (catégorie),
//                 v (vue: "etab"|"magasin"|"both"), perms (liste actions)
export const MODULES_CATALOG = [
  // === ÉTABLISSEMENT (PSAD client) ===
  { k: "patients", l: "Patients", ic: "ti-users", c: "Établissement", v: "etab",
    perms: ["read", "write", "delete", "export", "merge"], col: "#7a6fb0" },
  { k: "patient_dossier", l: "Dossier médical patient", ic: "ti-stethoscope", c: "Établissement", v: "etab",
    perms: ["read", "write", "delete", "export"], col: "#7a6fb0" },
  { k: "etablissement", l: "Établissement (fiche)", ic: "ti-building-hospital", c: "Établissement", v: "etab",
    perms: ["read", "write", "delete"], col: "#185FA5" },
  { k: "batiments", l: "Bâtiments / Services", ic: "ti-stack-2", c: "Établissement", v: "etab",
    perms: ["read", "write", "delete"], col: "#185FA5" },
  { k: "equipes", l: "Équipes soignantes", ic: "ti-users-group", c: "Établissement", v: "etab",
    perms: ["read", "write", "delete", "assign"], col: "#7a6fb0" },
  { k: "collaborateurs", l: "Collaborateurs (annuaire)", ic: "ti-id-badge-2", c: "Établissement", v: "etab",
    perms: ["read", "write", "delete"], col: "#185FA5" },
  { k: "prescripteurs", l: "Prescripteurs / Médecins", ic: "ti-prescription", c: "Établissement", v: "etab",
    perms: ["read", "write", "delete"], col: "#5aa05a" },

  // === MATÉRIEL & INTERVENTIONS ===
  { k: "materiels", l: "Matériel (parc)", ic: "ti-armchair-2", c: "Matériel", v: "etab",
    perms: ["read", "write", "delete", "export", "scan"], col: "#5a8f8f" },
  { k: "maintenance", l: "Maintenance préventive", ic: "ti-tool", c: "Matériel", v: "etab",
    perms: ["read", "write", "validate", "schedule"], col: "#EF9F27" },
  { k: "interventions", l: "Interventions / DI", ic: "ti-clipboard-list", c: "Matériel", v: "etab",
    perms: ["read", "write", "delete", "validate", "assign"], col: "#7CC8C8" },
  { k: "transferts", l: "Transferts de matériel", ic: "ti-transfer", c: "Matériel", v: "etab",
    perms: ["read", "write", "validate"], col: "#5a8f8f" },
  { k: "scan_bl", l: "Scan bon de livraison", ic: "ti-scan", c: "Matériel", v: "etab",
    perms: ["read", "write"], col: "#7CC8C8" },
  { k: "signalements", l: "Signalements", ic: "ti-alert-circle", c: "Matériel", v: "etab",
    perms: ["read", "write", "respond", "delete"], col: "#EF9F27" },

  // === COMMANDES / ACHATS ===
  { k: "commandes", l: "Commandes", ic: "ti-truck-delivery", c: "Achats", v: "etab",
    perms: ["read", "write", "validate", "cancel", "export"], col: "#5a8f8f" },
  { k: "achats", l: "Demandes d'achat", ic: "ti-shopping-cart", c: "Achats", v: "etab",
    perms: ["read", "write", "validate", "delete"], col: "#7CC8C8" },
  { k: "panier", l: "Panier / Catalogue magasin", ic: "ti-basket", c: "Achats", v: "etab",
    perms: ["read", "write"], col: "#5a8f8f" },
  { k: "promotions", l: "Promotions / Offres", ic: "ti-discount-2", c: "Achats", v: "both",
    perms: ["read", "write", "delete"], col: "#e35d5b" },

  // === MAGASIN (PSAD fournisseur) ===
  { k: "magasin_catalogue", l: "Catalogue magasin", ic: "ti-package", c: "Magasin", v: "magasin",
    perms: ["read", "write", "delete", "import", "export"], col: "#5a8f8f" },
  { k: "magasin_articles", l: "Articles magasin", ic: "ti-tag", c: "Magasin", v: "magasin",
    perms: ["read", "write", "delete", "price"], col: "#5a8f8f" },
  { k: "magasin_clients", l: "Clients / EC affiliés", ic: "ti-building-store", c: "Magasin", v: "magasin",
    perms: ["read", "write", "delete"], col: "#5a8f8f" },
  { k: "magasin_di", l: "DI / Demandes reçues", ic: "ti-inbox", c: "Magasin", v: "magasin",
    perms: ["read", "write", "validate", "assign"], col: "#7CC8C8" },
  { k: "magasin_bl", l: "Bons de livraison émis", ic: "ti-file-invoice", c: "Magasin", v: "magasin",
    perms: ["read", "write", "validate", "send"], col: "#EF9F27" },
  { k: "magasin_devis", l: "Devis", ic: "ti-receipt", c: "Magasin", v: "magasin",
    perms: ["read", "write", "send", "validate"], col: "#EF9F27" },
  { k: "magasin_inventaires", l: "Inventaires", ic: "ti-list-check", c: "Magasin", v: "magasin",
    perms: ["read", "write", "validate"], col: "#5a8f8f" },
  { k: "magasin_marketplace", l: "Marketplace promotions", ic: "ti-shopping-bag", c: "Magasin", v: "magasin",
    perms: ["read", "write"], col: "#e35d5b" },
  { k: "fournisseurs", l: "Fournisseurs", ic: "ti-building-warehouse", c: "Magasin", v: "magasin",
    perms: ["read", "write", "delete"], col: "#5a8f8f" },

  // === STOCK ===
  { k: "stock", l: "Stock / Inventaire", ic: "ti-packages", c: "Stock", v: "both",
    perms: ["read", "write", "adjust", "export"], col: "#5aa05a" },
  { k: "stock_alertes", l: "Alertes stock bas", ic: "ti-bell-ringing", c: "Stock", v: "both",
    perms: ["read", "configure"], col: "#EF9F27" },

  // === COMPTABILITÉ ===
  { k: "compta", l: "Comptabilité", ic: "ti-calculator", c: "Compta", v: "both",
    perms: ["read", "write", "validate", "export"], col: "#EF9F27" },
  { k: "compta_journaux", l: "Journaux comptables", ic: "ti-book-2", c: "Compta", v: "both",
    perms: ["read", "write", "validate"], col: "#EF9F27" },
  { k: "compta_periodes", l: "Périodes / Clôtures", ic: "ti-calendar-stats", c: "Compta", v: "both",
    perms: ["read", "write", "close"], col: "#EF9F27" },
  { k: "factures", l: "Factures / Avoirs", ic: "ti-file-dollar", c: "Compta", v: "both",
    perms: ["read", "write", "validate", "send", "export"], col: "#EF9F27" },

  // === PRÉSENTATION / KPI ===
  { k: "tv_mode", l: "Mode TV (présentation)", ic: "ti-device-tv", c: "Pilotage", v: "etab",
    perms: ["read"], col: "#142131" },
  { k: "statistiques", l: "Statistiques activité", ic: "ti-chart-bar", c: "Pilotage", v: "both",
    perms: ["read", "export"], col: "#185FA5" },
  { k: "statistiques_interv", l: "Stats interventions", ic: "ti-chart-line", c: "Pilotage", v: "etab",
    perms: ["read", "export"], col: "#7CC8C8" },
  { k: "vue_globale", l: "Vue globale dashboard", ic: "ti-layout-dashboard", c: "Pilotage", v: "etab",
    perms: ["read"], col: "#185FA5" },

  // === RGPD / SÉCURITÉ ===
  { k: "rgpd", l: "RGPD / Consentements", ic: "ti-shield-lock", c: "RGPD", v: "etab",
    perms: ["read", "write", "validate", "export"], col: "#5e4a8c" },
  { k: "rgpd_stats", l: "Statistiques RGPD", ic: "ti-shield-check", c: "RGPD", v: "etab",
    perms: ["read", "export"], col: "#5e4a8c" },
  { k: "audit", l: "Journal d'audit", ic: "ti-history", c: "RGPD", v: "both",
    perms: ["read", "export"], col: "#5e4a8c" },

  // === ADMINISTRATION ===
  { k: "utilisateurs", l: "Utilisateurs / Comptes", ic: "ti-user-circle", c: "Administration", v: "both",
    perms: ["read", "write", "delete", "invite"], col: "#142131" },
  { k: "roles", l: "Gestion des rôles", ic: "ti-key", c: "Administration", v: "both",
    perms: ["read", "write", "delete"], col: "#142131" },
  { k: "parametres", l: "Paramètres généraux", ic: "ti-settings", c: "Administration", v: "both",
    perms: ["read", "write"], col: "#5a6878" },
  { k: "integrations", l: "Intégrations (API/SI)", ic: "ti-plug", c: "Administration", v: "both",
    perms: ["read", "write", "test"], col: "#7a6fb0" },
  { k: "doublons", l: "Forcer doublons (avec commentaire)", ic: "ti-copy", c: "Administration", v: "both",
    perms: ["read", "write"], col: "#EF9F27" },
  { k: "collectivite", l: "Gestion collectivité (multi-étab)", ic: "ti-building-community", c: "Administration", v: "etab",
    perms: ["read", "write", "delete"], col: "#185FA5" },
  { k: "groupements", l: "Groupements (multi-magasins)", ic: "ti-building-skyscraper", c: "Administration", v: "magasin",
    perms: ["read", "write", "delete"], col: "#5a8f8f" },

  // === FORMATIONS / OUTILS ===
  { k: "formations", l: "Formations / Aveho Academy", ic: "ti-school", c: "Outils", v: "both",
    perms: ["read", "write"], col: "#7CC8C8" },
  { k: "agenda", l: "Agenda / Planning", ic: "ti-calendar-event", c: "Outils", v: "etab",
    perms: ["read", "write", "delete"], col: "#EF9F27" },
];

// === CATÉGORIES (pour groupement UI) ===
export const CATEGORIES = [
  { k: "Établissement", ic: "ti-building-hospital", col: "#185FA5" },
  { k: "Matériel", ic: "ti-armchair-2", col: "#5a8f8f" },
  { k: "Achats", ic: "ti-shopping-cart", col: "#7CC8C8" },
  { k: "Magasin", ic: "ti-building-store", col: "#5a8f8f" },
  { k: "Stock", ic: "ti-packages", col: "#5aa05a" },
  { k: "Compta", ic: "ti-calculator", col: "#EF9F27" },
  { k: "Pilotage", ic: "ti-chart-bar", col: "#185FA5" },
  { k: "RGPD", ic: "ti-shield-lock", col: "#5e4a8c" },
  { k: "Administration", ic: "ti-settings", col: "#142131" },
  { k: "Outils", ic: "ti-tool", col: "#7CC8C8" },
];

// === LABELS DES PERMISSIONS ===
export const PERM_LABELS = {
  read: { l: "Lecture", ic: "ti-eye", col: "#7CC8C8" },
  write: { l: "Écriture", ic: "ti-pencil", col: "#185FA5" },
  delete: { l: "Suppression", ic: "ti-trash", col: "#e35d5b" },
  validate: { l: "Validation", ic: "ti-check", col: "#5aa05a" },
  export: { l: "Export", ic: "ti-download", col: "#7a6fb0" },
  import: { l: "Import", ic: "ti-upload", col: "#5a8f8f" },
  invite: { l: "Inviter", ic: "ti-user-plus", col: "#185FA5" },
  assign: { l: "Assigner", ic: "ti-arrow-bar-right", col: "#EF9F27" },
  merge: { l: "Fusionner", ic: "ti-arrows-join", col: "#7a6fb0" },
  scan: { l: "Scanner", ic: "ti-scan", col: "#7CC8C8" },
  price: { l: "Tarifs", ic: "ti-tag", col: "#EF9F27" },
  schedule: { l: "Planifier", ic: "ti-calendar-time", col: "#EF9F27" },
  cancel: { l: "Annuler", ic: "ti-ban", col: "#e35d5b" },
  respond: { l: "Répondre", ic: "ti-message-reply", col: "#5aa05a" },
  adjust: { l: "Ajuster stock", ic: "ti-adjustments", col: "#5aa05a" },
  configure: { l: "Configurer", ic: "ti-settings-cog", col: "#5a6878" },
  close: { l: "Clôturer", ic: "ti-lock", col: "#5e4a8c" },
  send: { l: "Envoyer", ic: "ti-send", col: "#185FA5" },
  test: { l: "Tester", ic: "ti-test-pipe", col: "#7a6fb0" },
};

// === ICÔNES de RÔLES (à choisir pour personnaliser un rôle) ===
export const ROLE_ICONS = [
  { ic: "ti-crown", l: "Administrateur" },
  { ic: "ti-stethoscope", l: "Médecin" },
  { ic: "ti-nurse", l: "Infirmier" },
  { ic: "ti-user-shield", l: "Cadre santé" },
  { ic: "ti-clipboard-list", l: "Coordinateur" },
  { ic: "ti-calculator", l: "Comptable" },
  { ic: "ti-truck", l: "Logisticien" },
  { ic: "ti-package", l: "Magasinier" },
  { ic: "ti-building-store", l: "Vendeur magasin" },
  { ic: "ti-tools", l: "Technicien" },
  { ic: "ti-prescription", l: "Pharmacien" },
  { ic: "ti-id-badge-2", l: "Secrétaire" },
  { ic: "ti-eye", l: "Lecteur (consultation seule)" },
  { ic: "ti-chart-bar", l: "Analyste / KPI" },
  { ic: "ti-shield-lock", l: "DPO / RGPD" },
  { ic: "ti-user-circle", l: "Utilisateur standard" },
  { ic: "ti-users-group", l: "Équipe" },
  { ic: "ti-headphones", l: "Support" },
  { ic: "ti-building-bank", l: "Direction" },
  { ic: "ti-school", l: "Formateur" },
];

// === TEMPLATES DE RÔLES PRÉCONFIGURÉS ===
// Helper pour générer un objet droits avec toutes les perms d'un module
function fullPerms(moduleKey) {
  const mod = MODULES_CATALOG.find(m => m.k === moduleKey);
  return mod ? [...mod.perms] : [];
}
function readOnly() { return ["read"]; }
function readWrite() { return ["read", "write"]; }

export const ROLE_TEMPLATES = [
  // === SUPER ADMIN ===
  {
    nom: "Administrateur",
    description: "Accès complet à toutes les fonctionnalités du soft.",
    icone: "ti-crown",
    couleur: "#142131",
    side: "both",
    droits: Object.fromEntries(MODULES_CATALOG.map(m => [m.k, fullPerms(m.k)])),
  },

  // === CÔTÉ ÉTABLISSEMENT ===
  {
    nom: "Cadre de santé",
    description: "Pilote l'activité soignante : patients, équipes, interventions.",
    icone: "ti-user-shield",
    couleur: "#185FA5",
    side: "etab",
    droits: {
      patients: ["read", "write", "delete", "export"],
      patient_dossier: ["read", "write", "delete"],
      etablissement: ["read"],
      batiments: ["read"],
      equipes: fullPerms("equipes"),
      collaborateurs: ["read", "write"],
      prescripteurs: ["read"],
      interventions: fullPerms("interventions"),
      signalements: ["read", "write", "respond"],
      maintenance: ["read", "write", "schedule"],
      materiels: ["read"],
      transferts: ["read", "write"],
      commandes: ["read"],
      achats: ["read", "write", "validate"],
      vue_globale: ["read"],
      statistiques: ["read", "export"],
      statistiques_interv: ["read", "export"],
      agenda: ["read", "write"],
      rgpd: ["read", "write", "validate"],
      audit: ["read"],
    },
  },
  {
    nom: "Infirmier coordinateur",
    description: "Gestion quotidienne des patients et interventions.",
    icone: "ti-nurse",
    couleur: "#7CC8C8",
    side: "etab",
    droits: {
      patients: ["read", "write"],
      patient_dossier: ["read", "write"],
      equipes: ["read"],
      collaborateurs: ["read"],
      prescripteurs: ["read"],
      interventions: ["read", "write", "validate"],
      signalements: ["read", "write", "respond"],
      maintenance: ["read", "write"],
      materiels: ["read", "scan"],
      transferts: ["read", "write"],
      scan_bl: ["read", "write"],
      commandes: ["read"],
      achats: ["read", "write"],
      panier: ["read", "write"],
      agenda: ["read", "write"],
      rgpd: ["read", "write"],
    },
  },
  {
    nom: "Médecin / Prescripteur",
    description: "Accès dossier patient + prescriptions.",
    icone: "ti-stethoscope",
    couleur: "#5aa05a",
    side: "etab",
    droits: {
      patients: ["read", "write"],
      patient_dossier: ["read", "write"],
      prescripteurs: ["read", "write"],
      equipes: ["read"],
      collaborateurs: ["read"],
      interventions: ["read", "write"],
      signalements: ["read", "write"],
      materiels: ["read"],
      rgpd: ["read", "write"],
      agenda: ["read", "write"],
    },
  },
  {
    nom: "Secrétaire médicale",
    description: "Accueil et administration courante.",
    icone: "ti-id-badge-2",
    couleur: "#7a6fb0",
    side: "etab",
    droits: {
      patients: ["read", "write"],
      patient_dossier: ["read"],
      collaborateurs: ["read"],
      prescripteurs: ["read", "write"],
      interventions: ["read"],
      signalements: ["read"],
      commandes: ["read"],
      agenda: ["read", "write"],
    },
  },
  {
    nom: "Pharmacien",
    description: "Suivi des produits, traitements et nutrition.",
    icone: "ti-prescription",
    couleur: "#5aa05a",
    side: "etab",
    droits: {
      patients: ["read"],
      patient_dossier: ["read"],
      materiels: ["read"],
      stock: ["read", "write", "adjust"],
      stock_alertes: ["read", "configure"],
      commandes: ["read", "write"],
      achats: ["read", "write", "validate"],
      audit: ["read"],
    },
  },
  {
    nom: "Technicien matériel",
    description: "Installation, maintenance, transferts matériel.",
    icone: "ti-tools",
    couleur: "#5a8f8f",
    side: "etab",
    droits: {
      materiels: fullPerms("materiels"),
      maintenance: fullPerms("maintenance"),
      interventions: ["read", "write", "validate"],
      transferts: fullPerms("transferts"),
      scan_bl: fullPerms("scan_bl"),
      signalements: ["read", "write", "respond"],
      patients: ["read"],
      collaborateurs: ["read"],
    },
  },

  // === CÔTÉ MAGASIN (PSAD fournisseur) ===
  {
    nom: "Responsable magasin",
    description: "Pilotage complet du magasin / pôle Aveho.",
    icone: "ti-building-store",
    couleur: "#5a8f8f",
    side: "magasin",
    droits: {
      magasin_catalogue: fullPerms("magasin_catalogue"),
      magasin_articles: fullPerms("magasin_articles"),
      magasin_clients: fullPerms("magasin_clients"),
      magasin_di: fullPerms("magasin_di"),
      magasin_bl: fullPerms("magasin_bl"),
      magasin_devis: fullPerms("magasin_devis"),
      magasin_inventaires: fullPerms("magasin_inventaires"),
      magasin_marketplace: fullPerms("magasin_marketplace"),
      fournisseurs: fullPerms("fournisseurs"),
      promotions: fullPerms("promotions"),
      stock: fullPerms("stock"),
      stock_alertes: fullPerms("stock_alertes"),
      compta: ["read", "write"],
      factures: ["read", "write", "send"],
      statistiques: ["read", "export"],
      audit: ["read"],
      groupements: ["read"],
    },
  },
  {
    nom: "Magasinier / Préparateur",
    description: "Préparation commandes, BL, stock.",
    icone: "ti-package",
    couleur: "#5a8f8f",
    side: "magasin",
    droits: {
      magasin_catalogue: ["read"],
      magasin_articles: ["read"],
      magasin_di: ["read", "write", "validate"],
      magasin_bl: ["read", "write", "validate", "send"],
      magasin_inventaires: fullPerms("magasin_inventaires"),
      stock: fullPerms("stock"),
      stock_alertes: ["read"],
      scan_bl: ["read", "write"],
    },
  },
  {
    nom: "Commercial magasin",
    description: "Devis, clients, marketplace, promotions.",
    icone: "ti-headphones",
    couleur: "#7CC8C8",
    side: "magasin",
    droits: {
      magasin_catalogue: ["read"],
      magasin_articles: ["read", "price"],
      magasin_clients: fullPerms("magasin_clients"),
      magasin_devis: fullPerms("magasin_devis"),
      magasin_marketplace: fullPerms("magasin_marketplace"),
      promotions: fullPerms("promotions"),
      fournisseurs: ["read"],
      compta: ["read"],
      factures: ["read", "send"],
      statistiques: ["read"],
    },
  },

  // === RÔLES COMMUNS / SUPPORT ===
  {
    nom: "Comptable",
    description: "Compta, factures, journaux.",
    icone: "ti-calculator",
    couleur: "#EF9F27",
    side: "both",
    droits: {
      compta: fullPerms("compta"),
      compta_journaux: fullPerms("compta_journaux"),
      compta_periodes: fullPerms("compta_periodes"),
      factures: fullPerms("factures"),
      commandes: ["read", "export"],
      achats: ["read"],
      audit: ["read"],
      statistiques: ["read", "export"],
    },
  },
  {
    nom: "DPO / Référent RGPD",
    description: "Conformité RGPD, consentements, audit.",
    icone: "ti-shield-lock",
    couleur: "#5e4a8c",
    side: "both",
    droits: {
      rgpd: fullPerms("rgpd"),
      rgpd_stats: fullPerms("rgpd_stats"),
      audit: fullPerms("audit"),
      patients: ["read"],
      patient_dossier: ["read"],
      utilisateurs: ["read"],
      parametres: ["read"],
    },
  },
  {
    nom: "Analyste / Pilotage KPI",
    description: "Consultation des statistiques et dashboards.",
    icone: "ti-chart-bar",
    couleur: "#185FA5",
    side: "both",
    droits: {
      vue_globale: ["read"],
      statistiques: fullPerms("statistiques"),
      statistiques_interv: fullPerms("statistiques_interv"),
      rgpd_stats: ["read", "export"],
      audit: ["read"],
      patients: ["read"],
      materiels: ["read"],
      interventions: ["read"],
      commandes: ["read"],
      stock: ["read"],
      compta: ["read"],
    },
  },
  {
    nom: "Lecteur (consultation seule)",
    description: "Accès en lecture sur tout, écriture nulle part.",
    icone: "ti-eye",
    couleur: "#7a6fb0",
    side: "both",
    droits: Object.fromEntries(
      MODULES_CATALOG.map(m => [m.k, readOnly()])
    ),
  },
  {
    nom: "Direction",
    description: "Vue d'ensemble + statistiques + audit + validation.",
    icone: "ti-building-bank",
    couleur: "#142131",
    side: "both",
    droits: {
      patients: ["read", "export"],
      materiels: ["read", "export"],
      interventions: ["read", "export"],
      commandes: ["read", "validate", "export"],
      achats: ["read", "validate"],
      compta: ["read", "validate", "export"],
      factures: ["read", "validate", "export"],
      vue_globale: ["read"],
      statistiques: fullPerms("statistiques"),
      statistiques_interv: fullPerms("statistiques_interv"),
      rgpd_stats: ["read", "export"],
      audit: fullPerms("audit"),
      utilisateurs: ["read"],
      collectivite: ["read", "write"],
      groupements: ["read", "write"],
    },
  },
  {
    nom: "Formateur",
    description: "Gestion des formations Aveho Academy.",
    icone: "ti-school",
    couleur: "#7CC8C8",
    side: "both",
    droits: {
      formations: fullPerms("formations"),
      collaborateurs: ["read"],
      utilisateurs: ["read"],
    },
  },
];
